### ISSUE TITLE
LogIn page text edits

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#83]
@interrogator @witlox 
As the first step to getting the LogIn page ready for going live, please make the changes listed in the attached Word document. Many thanks, Martin
[LogInPage_28Oct19.docx](https://github.com/uzh/marugoto/files/3778786/LogInPage_28Oct19.docx)

**Comment by martindusinberre** [comment]
Here are some more edits to be made to the first page (and also second and third pages). The text to be added is in yellow (the non-yellow text is the same as that which I sent yesterday).
Thanks, Martin
[LogInPage_29Oct19.docx](https://github.com/uzh/marugoto/files/3783175/LogInPage_29Oct19.docx)

**Comment by interrogator** [comment]
Done in https://github.com/uzh/marugoto-frontend/pull/3

**Comment by martindusinberre** [comment]
@witlox @interrogator  This isn't appearing so I'm reopening it.

**Comment by witlox** [comment]
this time we also need to do the textual changes, not just content

**Comment by interrogator** [comment]
@witlox is this fixed by https://github.com/uzh/marugoto-frontend/commit/dde111a3fce2822efb8cc082f257a36664540502 ? close if so.

I'm looking at the docx, everything specified seems merged. I'm currently making sure hrefs get underlined, but that's not in scope of this issue

**Comment by martindusinberre** [comment]
@interrogator the front page is now updated--thanks. But the text I asked for on both the "My Games" and "Topic Selection" page is still not updated (see also my discussion in #88). Is this an update problem or did you forget to input the changes?

**Comment by martindusinberre** [comment]
@interrogator To avoid problems with desired textual changes in the future, I'll just cut and paste the relevant texts here:
This is for the **Your Games** page: please delete the two lines of text we currently have and replace them with this:
This is your Lives in Transit “home” page. You can start your game(s) from here and you can return here at any point by clicking on the “home” icon during game play. If you accidentally hit the “back” button on your browser, you will be returned here but your game choices will be automatically saved. You can then click on “Continue” to return to where you were in the topic. Or you can start a new game. When you finish a game, you will also return here and you can click on the “download” icon in order to save a copy of your Lives in Transit notebook.

**Comment by martindusinberre** [comment]
This is for the **Topic Selection** page: again, please delete the text we have now and replace it with this:
When “Lives in Transit” is launched in spring 2020, there will be a selection of topics for you to choose from here. Until the full launch, you can get a feel for the game by playing through a short extract from the beginning of the topic, “Defining Work”.

**Comment by martindusinberre** [comment]
Thanks!

**Comment by interrogator** [comment]
Confusion about this now clarified, I didn't see that there were two docxs. All docx notes are now in master branch I believe.

**Comment by martindusinberre** [comment]
For the "Citing LiT" tab, please add:
Dusinberre, Martin, and the UZH LiT Team (2020): "Lives in Transit" E-Learning Game, www.livesintransit.org
[or please amend "and the UZH LiT Team" if you find it clunky, but I think we should try and have UZH in there and there obviously needs to be some kind of "team" mention, too.]

**Comment by martindusinberre** [comment]
Actually, thinking ahead: we might want to refine this:

For overall citing of the Lives in Transit game:
Dusinberre, Martin, and the UZH LiT Team (2020): "Lives in Transit" E-Learning Game, www.livesintransit.org

For citing of specific topics, as follows:
[topic author et al], [topic title], in Dusinberre, Martin, and the UZH LiT Team (2020): "Lives in Transit" E-Learning Game, www.livesintransit.org
e.g. Dusinberre, Martin et al, "Defining Work", in Dusinberre, Martin, and the UZH LiT Team (2020): "Lives in Transit" E-Learning Game, www.livesintransit.org

**Comment by interrogator** [comment]
@lfeine are you a bibtex person? I'd like to have this in bibtex format too ideally...

**Comment by interrogator** [comment]
Citation info added at https://github.com/uzh/marugoto-frontend/pull/10/files

Closing, bibtex will go into #90
